name: Mark stale issues and PRs
on:
  schedule:
    - cron: "0 3 * * 1"
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 45
          days-before-close: 10
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: pinned
          exempt-pr-labels: pinned
          stale-issue-message: >
            This issue has been automatically marked as stale due to inactivity.
          stale-pr-message: >
            This pull request has been marked as stale due to inactivity.
